import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { Router, RouterLink } from '@angular/router';

@Component({
  selector: 'app-customer-register',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './customer-register.html',
  styleUrls: ['./customer-register.css'],
})
export class CustomerRegister implements AfterViewInit, OnDestroy {
  // Keep references to handlers so we can remove them
  private submitHandler = (e: Event) => this.onSubmit(e);
  private outsideClickHandler = (e: Event) => this.onWindowClick(e);
  private realTimeHandlers: { elId: string; handler: (e: Event) => void }[] = [];

  constructor(private router: Router) {}

  ngAfterViewInit(): void {
    // Initialize page - set max date for DOB to ensure 18+ years old
    const today = new Date();
    const maxDate = new Date(today.getFullYear() - 18, today.getMonth(), today.getDate());
    const dateString = maxDate.toISOString().split('T')[0];
    const dobEl = document.getElementById('dob') as HTMLInputElement | null;
    if (dobEl) {
      dobEl.max = dateString;
      // fill test value (optional)
      if (!dobEl.value) dobEl.value = '1990-01-01';
    }

    // autogenerate customer ID , immutable 
    const customerIdField = document.getElementById('ssn') as HTMLInputElement | null;
    if (customerIdField && !customerIdField.value) {
      customerIdField.value = this.generateCustomerId();
    }
    if (customerIdField) customerIdField.readOnly = true;

    // autogenerated account number , 10 digits 
    const accountNumberField = document.getElementById('accountNumber') as HTMLInputElement | null;
    if (accountNumberField && !accountNumberField.value) {
      accountNumberField.value = this.generateAccountNumber();
    }
    if (accountNumberField) accountNumberField.readOnly = true;

    // static IFSC
    const ifscCodeField = document.getElementById('ifscCode') as HTMLInputElement | null;
    if (ifscCodeField && !ifscCodeField.value) {
      ifscCodeField.value = 'PAYW0001234';
    }
    if (ifscCodeField) ifscCodeField.readOnly = true;

    // test defaults (can be removed)
    const aadharEl = document.getElementById('aadharNo') as HTMLInputElement | null;
    if (aadharEl && !aadharEl.value) aadharEl.value = '123456789012';
    
    const panEl = document.getElementById('panNo') as HTMLInputElement | null;
    if (panEl && !panEl.value) panEl.value = 'ABCDE1234F';
    
    const emailEl = document.getElementById('email') as HTMLInputElement | null;
    if (emailEl && !emailEl.value) emailEl.value = 'test@superbank.com';
    
    const addressEl = document.getElementById('address') as HTMLTextAreaElement | null;
    if (addressEl && !addressEl.value) addressEl.value = '123 Test Street, Test City';
    
    const contactEl = document.getElementById('contactNumber') as HTMLInputElement | null;
    if (contactEl && !contactEl.value) contactEl.value = '9234567890';

    // attach form submit handler
    const form = document.getElementById('customerForm') as HTMLFormElement | null;
    if (form) form.addEventListener('submit', this.submitHandler);

    // attach modal outside click handler
    window.addEventListener('click', this.outsideClickHandler);

    // attach modal continue button (replaces inline onclick)
    const modalBtn = document.getElementById('modalContinueBtn') as HTMLButtonElement | null;
    if (modalBtn) modalBtn.addEventListener('click', () => this.redirectDashboard());

    // Real-time validation handlers for certain fields
    const fields = ['ssn', 'customerFirstName', 'customerLastName', 'accountNumber', 'ifscCode', 'aadharNo', 'panNo'];
    fields.forEach((id) => {
      const el = document.getElementById(id) as HTMLInputElement | null;
      if (el) {
        const h = (e: Event) => {
          const t = e.target as HTMLInputElement;
          if (t && t.value.trim().length > 0) {
            const group = t.closest('.form-group');
            if (group) group.classList.remove('error');
          }
        };
        el.addEventListener('input', h);
        this.realTimeHandlers.push({ elId: id, handler: h });
      }
    });

    // email realtime
    const emailValidationEl = document.getElementById('email') as HTMLInputElement | null;
    if (emailValidationEl) {
      const h = (e: Event) => {
        const t = e.target as HTMLInputElement;
        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        if (emailRegex.test(t.value)) {
          const group = t.closest('.form-group');
          if (group) group.classList.remove('error');
        }
      };
      emailValidationEl.addEventListener('input', h);
      this.realTimeHandlers.push({ elId: 'email', handler: h });
    }

    // contact realtime
    const phoneEl = document.getElementById('contactNumber') as HTMLInputElement | null;
    if (phoneEl) {
      const h = (e: Event) => {
        const t = e.target as HTMLInputElement;
        const phoneRegex = /^[0-9]{10}$/;
        if (phoneRegex.test(t.value)) {
          const group = t.closest('.form-group');
          if (group) group.classList.remove('error');
        }
      };
      phoneEl.addEventListener('input', h);
      this.realTimeHandlers.push({ elId: 'contactNumber', handler: h });
    }

    // address realtime
    const addrEl = document.getElementById('address') as HTMLTextAreaElement | null;
    if (addrEl) {
      const h = (e: Event) => {
        const t = e.target as HTMLTextAreaElement;
        if (t.value.trim().length > 0) {
          const group = t.closest('.form-group');
          if (group) group.classList.remove('error');
        }
      };
      addrEl.addEventListener('input', h);
      this.realTimeHandlers.push({ elId: 'address', handler: h });
    }
  }

  ngOnDestroy(): void {
    const form = document.getElementById('customerForm') as HTMLFormElement | null;
    if (form) form.removeEventListener('submit', this.submitHandler);
    window.removeEventListener('click', this.outsideClickHandler);

    // remove modal continue binding if present
    const modalBtn = document.getElementById('modalContinueBtn') as HTMLButtonElement | null;
    if (modalBtn) modalBtn.removeEventListener('click', () => this.redirectDashboard());

    // remove realtime handlers
    this.realTimeHandlers.forEach(({ elId, handler }) => {
      const el = document.getElementById(elId);
      if (el) el.removeEventListener('input', handler);
    });
    this.realTimeHandlers = [];
  }

  // ---------- form logic methods (converted from inline script) ----------
  private generateCustomerId(): string {
    return Math.floor(1000000 + Math.random() * 9000000).toString();
  }

  private generateAccountNumber(): string {
    return Math.floor(1000000000 + Math.random() * 9000000000).toString();
  }

  private onSubmit(e: Event): void {
    e.preventDefault();
    this.clearErrors();

    const ssn = (document.getElementById('ssn') as HTMLInputElement | null)?.value.trim() ?? '';
    const first = (document.getElementById('customerFirstName') as HTMLInputElement | null)?.value.trim() ?? '';
    const last = (document.getElementById('customerLastName') as HTMLInputElement | null)?.value.trim() ?? '';
    const customerName = `${first}${last ? ' ' + last : ''}`.trim();
    const accountNumber = (document.getElementById('accountNumber') as HTMLInputElement | null)?.value.trim() ?? '';
    const ifscCode = (document.getElementById('ifscCode') as HTMLInputElement | null)?.value.trim() ?? '';
    const accountBalanceRaw = (document.getElementById('accountBalance') as HTMLInputElement | null)?.value ?? '';
    const accountBalance = accountBalanceRaw === '' ? '' : Number(accountBalanceRaw);
    const aadharNo = (document.getElementById('aadharNo') as HTMLInputElement | null)?.value.trim() ?? '';
    const panNo = (document.getElementById('panNo') as HTMLInputElement | null)?.value.trim() ?? '';
    const dob = (document.getElementById('dob') as HTMLInputElement | null)?.value ?? '';
    const gender = (document.getElementById('gender') as HTMLSelectElement | null)?.value ?? '';
    const maritalStatus = (document.getElementById('maritalStatus') as HTMLSelectElement | null)?.value ?? '';
    const email = (document.getElementById('email') as HTMLInputElement | null)?.value.trim() ?? '';
    const address = (document.getElementById('address') as HTMLTextAreaElement | null)?.value.trim() ?? '';
    const contactNumber = (document.getElementById('contactNumber') as HTMLInputElement | null)?.value.trim() ?? '';

    let isValid = true;

    if (!ssn) { this.showError('ssn', 'SSN ID is required'); isValid = false; }
    if (!customerName) { this.showError('customerFirstName', 'Customer name is required'); isValid = false; }
    if (!accountNumber) { this.showError('accountNumber', 'Account number is required'); isValid = false; }
    if (!ifscCode) { this.showError('ifscCode', 'IFSC code is required'); isValid = false; }

    if (accountBalance === '' || isNaN(Number(accountBalance)) || Number(accountBalance) < 0) {
      this.showError('accountBalance', 'Account balance must be a non-negative number');
      isValid = false;
    }

    const aadharRegex = /^[0-9]{12}$/;
    if (!aadharNo || !aadharRegex.test(aadharNo)) { this.showError('aadharNo', 'Aadhar number must be exactly 12 digits'); isValid = false; }

    const panRegex = /^[A-Z]{5}[0-9]{4}[A-Z]{1}$/;
    if (!panNo || !panRegex.test(panNo)) { this.showError('panNo', 'PAN must be 10 chars (format: AAAAA0000A)'); isValid = false; }

    if (!dob) { this.showError('dob', 'Date of birth is required'); isValid = false; }
    else {
      const dobDate = new Date(dob);
      const today = new Date();
      let age = today.getFullYear() - dobDate.getFullYear();
      const monthDiff = today.getMonth() - dobDate.getMonth();
      if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < dobDate.getDate())) age--;
      if (age < 18) { this.showError('dob', 'You must be at least 18 years old to create an account'); isValid = false; }
    }

    if (!gender) { this.showError('gender', 'Gender is required'); isValid = false; }
    if (!maritalStatus) { this.showError('maritalStatus', 'Marital status is required'); isValid = false; }
    const emailRegex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
    if (!email || !emailRegex.test(email)) { this.showError('email', 'Please enter a valid email address'); isValid = false; }
    if (!address || address.length === 0 || address.length > 200) { this.showError('address', 'Address is required (max 200 characters)'); isValid = false; }
    const phoneRegex = /^[0-9]{10}$/;
    if (!contactNumber || !phoneRegex.test(contactNumber)) { this.showError('contactNumber', 'Contact number must be exactly 10 digits'); isValid = false; }

    if (!isValid) return;

    const customerData = {
      ssn,
      name: customerName,
      accountNumber,
      ifscCode,
      balance: accountBalance,
      aadhar: aadharNo,
      pan: panNo,
      dob,
      gender,
      maritalStatus,
      email,
      address,
      contact: contactNumber,
      createdAt: new Date().toISOString(),
    };

    // persist customers safely
    try {
      const raw = localStorage.getItem('bankCustomers');
      let customers = [];
      try {
        customers = JSON.parse(raw || '[]') || [];
      } catch {
        customers = [];
      }
      if (customers.some((c: any) => String(c.ssn) === String(ssn))) {
        this.showError('ssn', 'This SSN ID already exists. Please use a different one.');
        return;
      }
      customers.push(customerData);
      localStorage.setItem('bankCustomers', JSON.stringify(customers));
      // fill modal details and show
      const modalSSN = document.getElementById('modalSSN');
      const modalName = document.getElementById('modalName');
      const modalAccount = document.getElementById('modalAccount');
      const modalEmail = document.getElementById('modalEmail');
      if (modalSSN) modalSSN.textContent = ssn;
      if (modalName) modalName.textContent = customerName;
      if (modalAccount) modalAccount.textContent = accountNumber;
      if (modalEmail) modalEmail.textContent = email;
      this.showSuccessModal();
    } catch (err) {
      console.error('Failed to save customer data', err);
      // show generic error
      this.showError('ssn', 'Failed to save customer data. See console.');
    }
  }

  private showError(fieldId: string, message: string): void {
    const el = document.getElementById(fieldId) as HTMLElement | null;
    const formGroup = el?.closest('.form-group') as HTMLElement | null;
    if (formGroup) {
      formGroup.classList.add('error');
      const errorMsg = formGroup.querySelector('.error-message') as HTMLElement | null;
      if (errorMsg) errorMsg.textContent = message;
    }
  }

  private clearErrors(): void {
    document.querySelectorAll('.form-group').forEach((group) => group.classList.remove('error'));
  }

  private showSuccessModal(): void {
    const modal = document.getElementById('successModal') as HTMLElement | null;
    if (modal) modal.style.display = 'block';
  }

  private redirectDashboard(): void {
    const ssn = (document.getElementById('ssn') as HTMLInputElement | null)?.value.trim() ?? '';
    const modal = document.getElementById('successModal') as HTMLElement | null;
    if (modal) modal.style.display = 'none';
    setTimeout(() => {
      this.router.navigate(['/customer-dashboard']);
    }, 300);
  }

  private onWindowClick(event: Event): void {
    const modal = document.getElementById('successModal') as HTMLElement | null;
    if (!modal) return;
    if (event.target === modal) modal.style.display = 'none';
  }
}
